import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import Image from "next/image";
import { useState, useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  // stored all filter options here
  const [coins, setCoins] = useState([]);
  const [sortBy, setSortBy] = useState(1);
  const [search, setSearch] = useState("");
  const [fdv, setFDV] = useState(100000000);

  const fetchCoins = async () => {
    if (process.env.NEXT_PUBLIC_API_URL) {
      const res = await axios.get(process.env.NEXT_PUBLIC_API_URL);
      setCoins(res.data);
      console.log(res.data);
    }
  };

  // fetching default setting responses
  useEffect(() => {
    fetchCoins();
  }, []);

  // adding and fetching filtered coin data
  const onSubmit = async () => {
    let url: any = process.env.NEXT_PUBLIC_API_URL;

    if (sortBy == 1) {
      url += "?sort_by=market_cap";
    }
    if (sortBy == 2) {
      url += "?sort_by=volume";
    }

    if (search) {
      url += "&search=" + search;
    }

    if (fdv !== 100000000) {
      url += "&fdv=" + fdv;
    }

    const res = await axios.get(url);
    setCoins(res.data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <div>
            <input
              className={styles.input}
              onChange={(e) => setFDV(Number(e.target.value))}
              placeholder="FDV Below... default $100m"
            />
            <input
              className={styles.input}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by name. eg eth for ethereum"
            />
            <select
              className={styles.input}
              onChange={(e) => setSortBy(Number(e.target.value))}
            >
              <option defaultChecked value={1}>
                Trade Volume
              </option>
              <option value={2}>Market Cap</option>
            </select>
            <button onClick={onSubmit} className={styles.button}>
              Submit
            </button>
          </div>
          <div className={styles.container}>
            {coins?.length > 0 ? (
              coins.map((coin: any, index) => (
                <div key={index}>
                  <Image
                    src={coin.image}
                    alt={coin.symbol}
                    width={100}
                    height={100}
                  />
                  <h2>{coin.name}</h2>
                </div>
              ))
            ) : (
              <div>Loading.</div>
            )}
          </div>
        </main>
        <footer className={styles.footer}>
          Spredo Full Stack Developer Test
        </footer>
      </div>
    </>
  );
}
